version: "3.7"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=my_super_secret_key_123  # Biến môi trường JWT_SECRET
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: